# Generated by Django 4.2.1 on 2023-06-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_remove_category_sex_category_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество штук')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_shop.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_shop.size')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товара',
            },
        ),
    ]
